AWSTemplateFormatVersion: 2010-09-09

Parameters:
  BranchName:
    Description: GitHub branch name
    Type: String
    Default: master
  RepositoryName:
    Description: GitHub repository name
    Type: String
    Default: CodePipeline
  GitHubOwner:
    Type: String
    Default: muhammadans341
  GitHubSecret:
    Type: String
    NoEcho: true
    Default: mjenaipta1
  GitHubOAuthToken:
    Type: String
    NoEcho: true
    Default: e5ddfec789f68ad9d09abfb9f7f24a5384b05e0c
  ApplicationName:
    Description: CodeDeploy application name
    Type: String
    Default: DemoApplication
  BetaFleet:
    Description: Fleet configured in CodeDeploy
    Type: String
    Default: DemoFleet

Resources:

  AppPipeline: 
    Type: AWS::CodePipeline::Pipeline 
    Properties: 
      Name: Devops-Trainee-pipeline
      RoleArn: !ImportValue all-roles-stack-codePipelineRole
      Stages:
        -
          Name: Source
          Actions:
            -
              Name: SourceAction

              ActionTypeId: 
                Category: Source 
                Owner: ThirdParty 
                Version: 1 
                Provider: GitHub

              OutputArtifacts:
                - Name: SourceOutput

              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref RepositoryName
                Branch: !Ref BranchName
                OAuthToken: !Ref GitHubOAuthToken
                PollForSourceChanges: false
              
              RunOrder: 1
        -
          Name: Build
          Actions:
            -
              Name: BuildAction

              ActionTypeId: 
                Category: Build 
                Owner: AWS 
                Version: 1 
                Provider: CodeBuild
              InputArtifacts:  
                -  
                  Name : SourceOutput
              OutputArtifacts:
                - 
                  Name: BuildSourceOutput

              Configuration:
                ProjectName : nbf-codeBuildApp-dev-692560313237
              
              RunOrder: 1
        -
          Name: Deploy
          Actions:
            -
              Name: ReleaseAction
              InputArtifacts: 
                -
                  Name: BuildSourceOutput
              ActionTypeId:
                Category: Deploy 
                Owner: AWS 
                Version: 1
                Provider: S3
              Configuration: 
                BucketName: codepipeline-deploy-bucket
                Extract: true
                

      ArtifactStore: 
        Type: S3 
        Location: codepipelinedestinationbucket

  AppPipelineWebhook:
    Type: AWS::CodePipeline::Webhook
    Properties:
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: !Ref GitHubOAuthToken
      Filters:
        - JsonPath: $.ref
          MatchEquals: refs/heads/{Branch}
      TargetPipeline: !Ref AppPipeline
      TargetAction: SourceAction
      Name: AppPipelineWebhook
      TargetPipelineVersion: !GetAtt 
        - AppPipeline
        - Version
      RegisterWithThirdParty: true
